# This volume holds your photos.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
spec:
  resources:
    requests:
      storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce

---

# This volume contains thumbnails. Setting it to 10-15% the size of "photos" is probably reasonable.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protected
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce

---

# The postgres volume holds all the metadata. If it's 1% the size of "photos," you're probably fine.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
